[package]
name = "sunrise-mavlink-server"
version = "0.1.66"
edition = "2024"
build = "build.rs"

[features]
default = []
gpio = []

[profile.release]
opt-level = "z"   # 优化大小
lto = true        # 链接时优化
codegen-units = 1 # 更好的优化
panic = "abort"   # 减小二进制大小
strip = true      # 去除符号表

[dependencies]
actix-web = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["sync", "fs", "rt-multi-thread"] }
chrono = "0.4"
anyhow = "1"
mavlink = { version = "0.16", features = ["ardupilotmega"] }
log = "0.4.29"
log4rs = "1.4.0"
nu-ansi-term = "0.50.3"
rumqttc = "0.25.1"
dotenv = "0.15"

# GPIO相关依赖（根据你的硬件平台选择）
# 对于树莓派等Linux平台
# rppal = { version = "0.17", optional = true }
# 对于嵌入式平台
# embedded-hal = { version = "1.0", optional = true }

[build-dependencies]
serde_json = "1.0"    # 构建脚本也需要
toml_edit = "0.25.11"
semver = "1.0.28"
chrono = "0.4"
